name: Daily Repository Update

on:
  schedule:
    - cron: '30 8 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Update status file (24f1002437@ds.study.iitm.ac.in)
        run: echo "Last updated on $(date -u)" > last_update.txt

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "24f1002437@ds.study.iitm.ac.in"

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add last_update.txt
          git commit -m "Automated daily update: $(date -u)" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
